added health check

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -14,6 +14,11 @@ on:
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
+env:
+  DOCKER_BUILDKIT: 1
+  DOCKER_BUILDKIT_PROGRESS: plain
+  COMPOSE_DOCKER_CLI_BUILD: 1
+  IMAGE_NAME: transplant-api
 jobs:
   test:
     if: ${{ !github.event.inputs.skip_lint }}
@@ -34,7 +39,7 @@ jobs:
           --health-timeout 5s
           --health-retries 5
     env:
-      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/transplant_db?sslmode=disable
+      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/transplant_db?sslmode=disable
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -50,7 +55,6 @@ jobs:
           poetry config virtualenvs.in-project true
       - name: Install dependencies
         run: poetry install --no-interaction --no-root
-
       - name: Check code formatting
         run: poetry run black transplantApp donation --check
       - name: Check import sorting
@@ -71,3 +75,42 @@ jobs:
       - name: Fail if tests failed
         if: ${{ steps.tests.outcome == 'failure' }}
         run: exit 1
+      - name: Setup docker buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Build image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          load: true
+          target: dev-runner
+          tags: |
+            ${{ env.IMAGE_NAME }}:dev
+            ${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
+            ${{ env.IMAGE_NAME }}:dev-${{ github.run_number }}
+          cache-from: type=gha,scope=backend
+          cache-to: type=gha,mode=max,scope=backend
+      - name: Run container
+        run: docker run -d \
+          --name ${{ env.IMAGE_NAME }} \
+          -p 8080:8080 \
+          --health-cmd "curl -f http://localhost:8080/health/" \
+          --health-interval 5s \
+          --health-timeout 3s \
+          --health-retries 5 \
+          -e DATABASE_URL=${{ env.DATABASE_URL }} \
+          ${{ env.IMAGE_NAME }}:dev
+      - name: Check container health
+        run: |
+          for i in {1..15}; do
+            STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ${{ env.IMAGE_NAME }})
+            if [ "$STATUS" = "\"healthy\"" ]; then
+              exit 0
+            fi
+            sleep 3
+          done
+          echo "API failed to start"
+          docker logs ${{ env.IMAGE_NAME }}
+          exit 1
+      - name: Stop container
+        if: always()
+        run: docker rm -f ${{ env.IMAGE_NAME }}
